### ISSUE TITLE
Site Rendering Issue

### ISSUE THREAD

**Issue by bidyutchanda** [jeromelachaud/freelancer-theme#95]
Hi. 
I just started using this theme. 
I already have a Jekyll theme running on https://bidyutchanda.github.io.
I wanted to make a gh-pages branch `portfolio` and host at https://bidyutchanda.github.io/portfolio. 

But the whole site is not being rendered properly.

This is what I get. 

![screenshot from 2019-01-05 00-25-38](https://user-images.githubusercontent.com/20928770/50705628-68684400-1081-11e9-80c1-f6ecae2f5993.png)

**Comment by bidyutchanda** [comment]
This is solved. I added `baseurl` parameter in `_config.yml`.

**Comment by TheGolfLab** [comment]
@jeromelachaud I'm getting similar behavior to this, but setting the ```baseurl``` doesn't fix it. I still get errors when loading the ```*.js``` resources.

Any ideas?

![image](https://user-images.githubusercontent.com/68299395/87479852-3599f700-c5fa-11ea-8c78-e585982af717.png)
